
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tywwuwbzlofgncqxzkid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5d3d1d2J6bG9mZ25jcXh6a2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTIwMjcsImV4cCI6MjA1OTg2ODAyN30.0l9s1_WV0PenGvFb13zc-tGY-NTweYd78XnLjQbeYAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
